--DEMEOSERVER
--USE DEMEO
select * from cliente where ce_codigocliente = '53228'

select * from [dmac28].[dmac_loja].[dbo].fin_cliente where ce_codigocliente = '53228'
--SE CLIENTE EXISTIR NA LOJA, EXCLUIR 
--DELETE [dmac28].[dmac_loja].[dbo].fin_cliente where ce_codigocliente = '53228'

insert into [dmac28].[dmac_loja].[dbo].fin_cliente 
(CE_CodigoCliente,
CE_CGC,
CE_InscricaoEstadual,
CE_Razao,
CE_Endereco,
CE_Bairro,
CE_Municipio,
CE_Estado,
CE_CEP,
CE_Telefone,
CE_Fax,
CE_EMail,
CE_TipoPessoa,
CE_Praca,
CE_PagamentoCarteira,
CE_EnderecoCobranca,
CE_BairroCobranca,
CE_MunicipioCobranca,
CE_EstadoCobranca,
CE_CEPCobranca,
CE_LimiteCredito,
CE_DataLimiteCredito,
CE_MaiorCompra,
CE_DataMaiorCompra,
CE_UltimaCompra,
CE_DataUltimaCompra,
CE_UltimoPagamento,
CE_DataUltimoPagamento,
CE_MaiorAtraso,
CE_QuantidadeCompras,
CE_JurosCartorio,
CE_DataCadastro,
CE_DataCancelamento,
CE_Alteracao,
CE_Situacao,
CE_HoraManutencao,
CE_Numero,
CE_CodigoFidelidade,
CE_PontosFidelidade,
CE_InscricaoEstadualSuframa) 
select CE_CodigoCliente,
CE_CGC,
CE_InscricaoEstadual,
CE_Razao,
CE_Endereco,
CE_Bairro,
CE_Municipio,
CE_Estado,
CE_CEP,
CE_Telefone,
CE_Fax,
CE_EMail,
CE_TipoPessoa,
CE_Praca,
CE_PagamentoCarteira,
CE_EnderecoCobranca,
CE_BairroCobranca,
CE_MunicipioCobranca,
CE_EstadoCobranca,
CE_CEPCobranca,
CE_LimiteCredito,
CE_DataLimiteCredito,
CE_MaiorCompra,
CE_DataMaiorCompra,
CE_UltimaCompra,
CE_DataUltimaCompra,
CE_UltimoPagamento,
CE_DataUltimoPagamento,
CE_MaiorAtraso,
CE_QuantidadeCompras,
CE_JurosCartorio,
CE_DataCadastro,
CE_DataCancelamento,
CE_Alteracao,
CE_Situacao,
CE_HoraManutencao,
CE_Numero,
CE_CodigoFidelidade,
CE_PontosFidelidade,
CE_InscricaoEstadualSuframa 
from cliente 
where ce_codigocliente = '53228'
